server:
  address: 0.0.0.0
  port: 8386
  servlet:
    context-path: /restaurant

spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/restaurant_service}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-8.0.41:3306/restaurant_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  #    url: jdbc:mysql://mysql:3306/restaurant_service
  #    username: root
  #    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "Uq03ySv0b1Ewz7fIVGFNNo/HbXQjdHMH0kkvMIgtmJ6dyI/pg2FS1r0Wl/y8PkPV"
  valid-duration: 2 # Hours
  refreshable-duration: 30 # Days